export enum SchedulerFeature {
    CellEdit = "cellEdit",
    ColumnLines = "columnLines",
    Dependencies = "dependencies",
    EventDrag = "eventDrag",
    EventContextMenu = "eventContextMenu",
    EventDragCreate = "eventDragCreate",
    EventEdit = "eventEdit",
    EventFilter = "eventFilter",
    EventResize = "eventResize",
    EventTooltip = "eventTooltip",
    Group = "group",
    GroupSummary = "groupSummary",
    HeaderContextMenu = "headerContextMenu",
    Labels = "labels",
    NonWorkingTime = "nonWorkingTime",
    RegionResize = "regionResize",
    Sort = "sort",
    ScheduleTooltip = "scheduleTooltip",
    Stripe = "stripe",
    Summary = "summary",
    TimeRanges = "timeRanges",
}
